namespace Acme.hello.Platform.Generic.Domain.Model.Entities;
/// <summary>
/// Represents a Developer entity in the 'Generic'bounded context with an autogenerated ID 
/// </summary>
public class Developer
{
    public Developer(string firstName, string lastName)
    {
        firstName = string.IsNullOrWhiteSpace(firstName) ? string.Empty : firstName.Trim();
        lastName = string.IsNullOrWhiteSpace(lastName) ? string.Empty : lastName.Trim();
    }
    
    /// <summary>
    /// Returns the full name by concatenating first and last name with a space.
    /// </summary>
    /// <returns>The full name of the developer.</returns>
    public string GetFullName() => $"{FirstName} {LastName}";

    /// <summary>
    /// Checks if either the first name or the last name is empty after trimming.
    /// </summary>
    /// <returns>True if either name is empty; otherwhise, false.</returns>
    public bool IsAnyNameEmpty() => string.IsNullOrEmpty(FirstName) || string.IsNullOrEmpty(LastName);
    public Guid Id { get; } = Guid.NewGuid();
    public string FirstName { get; }
    public string LastName { get; }
}